<?xml version="1.0" encoding="utf-8"?><Database Name="HistoryGameDataBase" Class="HistoryGameDataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Services\DB\HistoryGameDataBase.mdf;Integrated Security=True" SettingsObjectName="Connect_Four_Client.Properties.Settings" SettingsPropertyName="HistoryGameDataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HistoryGameTbl" Member="HistoryGameTbls">
    <Type Name="HistoryGameTbl">
      <Column Name="GameId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MoveNum" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Col" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YellowTool" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>